version: '3.8'

networks:
  icingaNet:
    name: icingaNet
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
volumes:
  - influxdb
  - grafana
  - bbdd
  - web #TODO script persistent startup web-setup config for web container and eliminate this volume

services:
  master1:
    image: sandrosano/icingamaster0-1 
    # user: root:root
    container_name: master1
    hostname: master1
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true #important to run systemd inside container
    # depends_on:
    networks: 
      - icingaNet:
        - ipv4_address: 172.18.0.10
  
  master2:
    image: sandrosano/icingamaster0-1 
    user: root:root
    container_name: master2
    hostname: master2
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true #important to run systemd inside container
    networks:
      - icingaNet:
      - ipv4_address: 172.18.0.11
  

  web:
    image: ./web
    container_name: web
    hostname: web
    volumes: web
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 172.18.0.11
  bbdd:
    image: ./bbdd
    container_name: bbdd
    hostname: bbdd
    volumes: bbdd
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 172.18.0.12

  sonda:
    image: ./sonda
    container_name: sonda
    hostname: sonda
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 172.18.0.16

  winproxy:
    image: ./sonda
    container_name: sonda
    hostname: sonda
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 172.18.0.15

####TODO : finish influx and grafana setup
  # influx:
  #   image: ./influx
  #   container_name: influx
  #   hostname: influx
  #   volumes:
  #   depends_on:
  #   ports:
  #   networks: 
  #     icingaNet:
  #       ipv4_address: 172.18.0.13
  # grafana:
  #   image: ./grafana
  #   container_name: grafana
  #   hostname: grafana
  #   volumes:
  #   depends_on:
  #   ports:
  #   networks: 
  #     icingaNet:
  #       ipv4_address: 172.18.0.14
  