version: '0.1'
services:
  master1:
    image: ./master
    container_name: master1
    hostname: master1
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 172.18.0.10
    # command: [sed, -i '/agentaddress/c\agentaddress 0.0.0.0" /etc/snmpd/snmpd.conf ]
  
  master2:
    image: ./master
    container_name: master2
    hostname: master2
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 172.18.0.11
  web:
    image: ./web
    container_name: web
    hostname: web
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 10.18.0.11
  bbdd:
    image: ./bbdd
    container_name: bbdd
    hostname: bbdd
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 10.18.0.12
  influx:
    image: ./influx
    container_name: influx
    hostname: influx
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 10.18.0.13
  grafana:
    image: ./grafana
    container_name: grafana
    hostname: grafana
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 10.18.0.14
  sonda:
    image: ./sonda
    container_name: sonda
    hostname: sonda
    volumes:
    depends_on:
    ports:
    networks: 
      icingaNet:
        ipv4_address: 10.18.0.15